return {
	NOTHING = "NOTHING",
	RESOURCE = "RESOURCE",
	INCOME = "INCOME",
	PLANET_PARAM = "PLANET_PARAM",
	PLACE_THE_TILE = "PLACE_THE_TILE",
	RESOURCE_ON_CARD = "RESOURCE_ON_CARD",
	SELL_CARDS = "SELL_CARDS",
}