local C = require("utils.message_ids")

return {
	GOLD = C.RECOURCE_GOLD,
	STEEL = C.RECOURCE_STEEL,
	TITANIUM = C.RECOURCE_TITANIUM,
	PLANT = C.RECOURCE_PLANT,
	ELECTRICITY = C.RECOURCE_ELECTRICITY,
	HEAT = C.RECOURCE_HEAT,
}